include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Error rules
    avoid_print: true
    avoid_returning_null_for_void: true
    cancel_subscriptions: true
    close_sinks: true
    valid_regexps: true
    
    # Style rules
    always_declare_return_types: true
    always_put_required_named_parameters_first: true
    annotate_overrides: true
    avoid_init_to_null: true
    avoid_null_checks_in_equality_operators: true
    avoid_unused_constructor_parameters: true
    await_only_futures: true
    camel_case_types: true
    constant_identifier_names: true
    empty_constructor_bodies: true
    library_names: true
    library_prefixes: true
    non_constant_identifier_names: true
    prefer_adjacent_string_concatenation: true
    prefer_collection_literals: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_interpolation_to_compose_strings: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_single_quotes: true
    require_trailing_commas: true
    sort_constructors_first: true
    unnecessary_brace_in_string_interps: true
    unnecessary_const: true
    unnecessary_new: true
    unnecessary_null_in_if_null_operators: true
    unnecessary_this: true
    use_rethrow_when_possible: true

analyzer:
  errors:
    # Treat missing returns as errors
    missing_return: error
    # Treat unused imports as errors
    unused_import: error
    # Allow TODOs
    todo: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
